name: Build and upload to PyPI

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: "Build wheels on ${{ matrix.arch }} for ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [auto]
        include:
          - os: ubuntu-latest
            arch: aarch64
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v1
        if:  ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU
      - name: "Build wheels"
        uses: "pypa/cibuildwheel@v2.3.1"
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_SKIP: "pp*"  # FIXME
          CIBW_BEFORE_BUILD: "pip install -U cython && ./update_cpp.sh"
          CIBW_BEFORE_BUILD_WINDOWS: "pip install -U cython && update_cpp.sh"
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest {project}/tests --doctest-modules"
      - uses: "actions/upload-artifact@v3"
        with:
          path: "./wheelhouse/*.whl"

  make_sdist:
    name: "Build source distribution"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
        with:
          submodules: true
      - name: "Install dependencies"
        run: "python -m pip install --upgrade cython"
      - name: "Rebuild CPP files using Cython"
        run: "./update_cpp.sh"
      - name: "Build source distribution"
        run: "pipx run build --sdist"
      - uses: "actions/upload-artifact@v3"
        with:
          path: "./dist/*.tar.gz"

  upload_to_pypi:
    name: "Upload to PyPI"
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - build_wheels
      - make_sdist
    steps:
      - uses: "actions/download-artifact@v3"
        with:
          name: artifact
          path: dist
      - uses: "pypa/gh-action-pypi-publish@v1.5.0"
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          print_hash: true
          verbose: true
          skip_existing: true
